### ISSUE TITLE
Chapitre Installation : npm build Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by acidjames** [falkodev/tuto-symfony-react-webpack-babel#1]
Bonjour,

lors du chapitre installation, on nous indique de créer un fichier app.js vide. 

Visiblement lorsque l'on npm start, l'erreur suivante apparait : 

```
ERROR in ./app/Resources/js/app.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/james/PhpstormProjects/react/react-symfony/app/Resources/js
 @ ./app/Resources/js/app.js 1:330-361
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.67 kB [rendered]
        [0] ./~/css-loader!./~/sass-loader!./app/Resources/scss/style.scss 160 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
webpack: Failed to compile.
```

Que doit-on mettre dans le fichier app.js pour que le webpack se build correctement ?

En te remerciant,
James

**Comment by falkodev** [comment]
Hello,


J'ai l'impression qu'il s'agit d'un problème de versions entre React et le Hot Loader. React, Webpack et beaucoup d'outils ont évolué depuis l'écriture de ce tuto.

Voici tout de même la suggestion trouvée ici : https://github.com/gaearon/react-hot-loader/issues/417

"Adding alias: { 'react/lib/ReactMount': 'react-dom/lib/ReactMount' } to your webpack config fixes this for now."


Sinon passer à la version 3 de React Hot Loader. Dis-moi si ça résoud le problème, sinon je creuserai un peu plus.

________________________________
De : James <notifications@github.com>
Envoyé : mercredi 28 juin 2017 10:58:09
À : falkodev/tuto-symfony-react-webpack-babel
Cc : Subscribed
Objet : [falkodev/tuto-symfony-react-webpack-babel] Chapitre Installation : npm build Cannot resolve module 'react/lib/ReactMount' (#1)


Bonjour,

lors du chapitre installation, on nous indique de créer un fichier app.js vide.

Visiblement lorsque l'on npm start, l'erreur suivante apparait :

ERROR in ./app/Resources/js/app.js
Module not found: Error: Cannot resolve module 'react/lib/ReactMount' in /home/james/PhpstormProjects/react/react-symfony/app/Resources/js
 @ ./app/Resources/js/app.js 1:330-361
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 1.67 kB [rendered]
        [0] ./~/css-loader!./~/sass-loader!./app/Resources/scss/style.scss 160 bytes {0} [built]
        [1] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
webpack: Failed to compile.


Que doit-on mettre dans le fichier app.js pour que le webpack se build correctement ?

En te remerciant,
James

**Comment by acidjames** [comment]
Merci pour ton aide, j'ai trouvé la solution 

dans package.json : 

`"react-hot-loader": "1.3.1",`

au lieu de la 1.3.0 :)
